# alacritty/alacritty.toml: Alacritty terminal config

[general]
import = ["./theme.default.toml"]

[window]
blur = true
decorations = "Transparent"
dynamic_padding = true
opacity = 0.89
option_as_alt = "Both"
padding = { x = 5, y = 4 }

[scrolling]
history = 20000
multiplier = 2

[font]
size         = 12.5
offset       = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
normal       = { family = 'RecMonoSmCasual Nerd Font', style = "Regular" }
bold         = { family = 'RecMonoSmCasual Nerd Font', style = "Bold" }
italic       = { family = 'RecMonoSmCasual Nerd Font', style = "Italic" }
bold_italic  = { family = 'RecMonoSmCasual Nerd Font', style = "Bold Italic" }
builtin_box_drawing = false

[terminal]
shell = { program = "/usr/bin/zsh", args = ["-l"] }

[bell]
animation = "EaseOutSine"
color = "#0f0f0f"
duration = 25

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[cursor]
blink_timeout = 0
blink_interval = 625
unfocused_hollow = true

[cursor.vi_mode_style]
shape = "Beam"
blinking = "Off"

[cursor.style]
shape = "Beam"
blinking = "On"
