[collections]
directory = 'Collections'

[collections.spec.0]
name = 'cyberdream.nvim:extras'
source = 'cyberdream.nvim'
filter = { depth = 1, search-path = 'extras'}

[collections.spec.1]
name = 'iTerm2-Color-Schemes'
source = 'iTerm2-Color-Schemes'
filter = { depth = 1, exclude = ['gh-pages', 'screenshots', 'tools'] }

[sources]
directory = 'Sources'

[sources.spec.0]
name = 'cyberdream.nvim'
type = 'git'
source = { url = 'https://github.com/scottmckendry/cyberdream.nvim.git', ref = 'main' }

[sources.spec.1]
name = 'iTerm2-Color-Schemes'
type = 'git'
source = { url = 'https://github.com/mbadolato/iTerm2-Color-Schemes.git', ref = 'master' }
