[collections]
directory = '~/.config/colorschemes/Collections'

[[collections.spec]]
name = 'cyberdream.nvim:extras'
source = 'cyberdream.nvim'
filter = { paths = ['extras'] }

[[collections.spec]]
name = 'iTerm2-Color-Schemes'
source = 'iTerm2-Color-Schemes'
filter = { exclude = ['gh-pages', 'screenshots', 'tools'] }

[[collections.spec]]
name = 'tokyonight.nvim:extras'
source = 'tokyonight.nvim'
filter = { paths = ['extras'] }

[sources]
directory = '~/.config/colorschemes/Sources'

[[sources.spec]]
name = 'cyberdream.nvim'
type = 'git'
source = { url = 'https://github.com/scottmckendry/cyberdream.nvim.git', ref = 'main' }

[[sources.spec]]
name = 'iTerm2-Color-Schemes'
type = 'git'
source = { url = 'https://github.com/mbadolato/iTerm2-Color-Schemes.git', ref = 'master' }

[[sources.spec]]
name = 'tokyonight.nvim'
type = 'git'
source = { url = "https://github.com/folke/tokyonight.nvim.git", ref = 'main' }
