# Don't print a new line at the start of the prompt
add_newline = false
# Pipes â•°â”€ â•­â”€
# Powerline symbols î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’
# Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# Random noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—
# Cool stuff ó°œ¥ î©± ï‹ ï€

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """\
$username$hostname\
$directory\
$git_branch$git_status\
$character"""

[line_break]
disabled = false

[character]
success_symbol = "\nâ•°ó°‡˜[î©± ï‹](bold fg:blue)"
error_symbol = "\nâ•°ó°‡˜[ï€ ï‹](bold fg:red)"

[username]
show_always = true
style_user = "bg:white fg:black"
style_root = "bg:white fg:red bold"
format = "â•­ó°‡˜ïƒ™[î‚¶](fg:white)[$user]($style)[î‚¼](fg:white bg:cyan)"

[hostname]
style = "bg:cyan fg:black"
format =  "[$hostname]($style)[î‚´](fg:cyan)"
ssh_only = false
trim_at = ".localdomain"

[directory]
style = "bg:green fg:black"
truncation_length = 5
truncation_symbol = "â€¦/"
format = "\nâ”œó°‡˜ïƒ™[î‚¶](fg:green)[ó°‰‹ $path]($style)[î‚´](fg:green)"

[git_branch]
style = "bg:yellow fg:black"
symbol = "ï˜"
truncation_length = 18
truncation_symbol = "â€¦"
format = "\nâ”œó°‡˜ïƒ™[î‚¶](fg:yellow)[$symbol $branch:[($remote_branch)](italic $style)]($style)[î‚¼](fg:yellow bg:purple)"

[git_status]
style = "bg:purple fg:black"
format = "[$all_status[$ahead_behind](italic $style)]($style)[î‚´](fg:purple)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï—"

[cmd_duration]
min_time = 0
format = "[î‚¶](bold fg:yellow)[ó°ª¢ $duration](bold bg:yellow fg:black)[î‚´](bold fg:yellow)"

[time]
disabled = true
format = "ğŸ•™[\\[ $time \\]]($style) "
time_format = "%T"

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

