format = """
[╭](fg:current_line)$username$hostname$fill$cmd_duration$python$aws$line_break\
[│](fg:current_line)$line_break\
[│](fg:current_line)$directory$git_branch$git_status$fill$time$line_break\
[│](fg:current_line)$line_break\
[╰](fg:current_line)$character\
"""

palette = 'dracula'
add_newline = true

[palettes.dracula]
foreground = '#F8F8F2'
background = '#282A36'
current_line = '#44475A'
primary = '#1E1F29'
box = '#44475A'
blue = '#6272A4'
cyan = '#8BE9FD'
green = '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red = '#FF5555'
yellow = '#F1FA8C'

[os]
format = '[•](fg:current_line)[](fg:blue)[$symbol ](fg:primary bg:blue)[](fg:blue)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[username]
format = '[•](fg:current_line)[](fg:pink)[ ](fg:bold fg:primary bg:pink)[](fg:pink bg:box)[ $user](fg:foreground bg:box)[](fg:box)'
show_always = true

[hostname]
format =  "[•](fg:current_line)[](fg:cyan)[ ](fg:bold fg:primary bg:cyan)[](fg:cyan bg:box)[ $hostname](fg:foreground bg:box)[](fg:bold fg:box)"
ssh_only = false
# trim_at = ".*"
disabled = false

[nodejs]
format = '[•](fg:current_line)[](fg:cyan)[$symbol](fg:bold fg:primary bg:cyan)[](fg:cyan bg:box)[ node.js:$version](fg:foreground bg:box)[](fg:box)'
symbol = '󰎙 '

[python]
format = '[•](fg:current_line)[](fg:yellow)[$symbol](fg:bold fg:primary bg:yellow)[](fg:yellow bg:box)[ python:$version](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[c]
format = '[•](fg:current_line)[](fg:blue)[$symbol](fg:bold fg:primary bg:red)[](fg:red bg:box)[ C:$version](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[aws]
format = '[•](fg:current_line)[](fg:purple)[$symbol](fg:bold fg:primary bg:purple)[](fg:purple bg:box)[ aws $profile](fg:foreground bg:box)[](fg:box)'
symbol = '󰖐 '

[fill]
# symbol = '─'
symbol = '•'
style = 'fg:current_line'

[directory]
format = '[•](fg:current_line)[](fg:green)[󰷏 ](fg:bold fg:primary bg:green)[](fg:green bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
home_symbol = " ~"
truncation_symbol = ' '
truncation_length = 28
fish_style_pwd_dir_length = 1
read_only = '󱧵 '
read_only_style = ''

[git_branch]
format = '[•](fg:current_line)[](fg:red)[$symbol](fg:bold fg:primary bg:red)[](fg:red bg:box)[ $branch](fg:foreground bg:box)'
symbol = ' '

[git_status]
format = '[( $all_status)](fg:foreground bg:box)[](fg:box)'

[cmd_duration]
min_time = 500
format = '[•](fg:current_line)[](fg:green)[ ](fg:bold fg:primary bg:green)[](fg:green bg:box)[ $duration](fg:foreground bg:box)[](fg:box)'

[shell]
format = '[•](fg:current_line)[](fg:cyan)[ ](fg:bold fg:primary bg:cyan)[](fg:cyan bg:box)[ $indicator](fg:foreground bg:box)[](fg:box)'
disabled = false

[time]
format = '[•](fg:current_line)[](fg:orange)[ ](fg:bold fg:primary bg:orange)[](fg:orange bg:box)[ $time](fg:foreground bg:box)[](fg:box)'
time_format = '%H:%M'
disabled = false

[character]
format = "[•$symbol](fg:current_line) "
success_symbol = '[  ](fg:green)'
error_symbol = '[  ](fg:red)'
