format = """
[╭](fg:current_line)$username$hostname$cmd_duration$fill$python$aws$line_break\
[│](fg:current_line)$directory$git_branch$git_status$fill$time$line_break\
[╰](fg:current_line)$character\
"""

palette = 'dracula'
add_newline = true

[palettes.dracula]
foreground = '#F8F8F2'
background = '#282A36'
current_line = '#44475A'
primary = '#1E1F29'
box = '#44475A'
blue = '#6272A4'
cyan = '#8BE9FD'
green = '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red = '#FF5555'
yellow = '#F1FA8C'

[os]
format = '[•](fg:current_line)[󱝂 ](fg:blue)[$symbol ](fg:primary)[ ](fg:blue)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[username]
format = '[•](fg:current_line)[󱝂 ](fg:pink)[ ](fg:bold fg:primary)[ ](fg:pink)[$user](fg:bold fg:foreground)[ ](fg:pink)'
show_always = true

[hostname]
format =  "[•](fg:current_line)[󱝂 ](fg:cyan)[ ](fg:bold fg:primary)[ ](fg:cyan)[$hostname](fg:bold fg:foreground)[ ](fg:cyan)"
ssh_only = false
# trim_at = ".*"
disabled = false

[nodejs]
format = '[•](fg:current_line)[󱝂 ](fg:cyan)[$symbol](fg:bold fg:primary)[ ](fg:cyan)[node.js:$version](fg:bold fg:foreground)[ ](fg:cyan)'
symbol = '󰎙 '

[python]
format = '[•](fg:current_line)[󱝂 ](fg:orange)[$symbol](fg:bold fg:primary)[ ](fg:orange)[python:$version](fg:bold fg:foreground)[ ](fg:orange)'
symbol = ' '

[c]
format = '[•](fg:current_line)[󱝂 ](fg:blue)[$symbol](fg:bold fg:primary)[ ](fg:blue)[C:$version](fg:bold fg:foreground)[ ](fg:blue)'
symbol = ' '

[aws]
format = '[•](fg:current_line)[󱝂 ](fg:purple)[$symbol](fg:bold fg:primary)[ ](fg:purple)[aws $profile](fg:bold fg:foreground)[ ](fg:purple)'
symbol = '󰖐 '

[fill]
# symbol = '─'
symbol = '•'
style = 'fg:current_line'

[directory]
format = '[•](fg:current_line)[󱝂 ](fg:green)[󰷏 ](fg:bold fg:primary)[ ](fg:green)[$read_only$truncation_symbol$path](fg:bold fg:foreground)[ ](fg:cyan)'
home_symbol = " ~"
truncation_symbol = ' '
truncation_length = 28
fish_style_pwd_dir_length = 1
read_only = '󱧵 '
read_only_style = ''

[git_branch]
format = '[•](fg:current_line)[󱝂 ](fg:red)[$symbol](fg:bold fg:primary)[ ](fg:red)[$branch](fg:bold fg:foreground)'
symbol = ' '

[git_status]
format = '[( $all_status)](fg:bold fg:foreground)[ ](fg:red)'

[cmd_duration]
min_time = 500
format = '[•](fg:current_line)[󱝂 ](fg:green)[ ](fg:bold fg:primary)[ ](fg:green)[$duration](fg:bold fg:foreground)[ ](fg:green)'

[shell]
format = '[•](fg:current_line)[󱝂 ](fg:cyan)[ ](fg:bold fg:primary)[ ](fg:cyan)[$indicator](fg:bold fg:foreground)[ ](fg:cyan)'
disabled = false

[time]
format = '[•](fg:current_line)[󱝂 ](fg:yellow)[ ](fg:bold fg:primary)[ ](fg:yellow)[$time](fg:bold fg:foreground)[ ](fg:yellow)'
time_format = '%H:%M'
disabled = false

[character]
format = "[•$symbol](fg:current_line) "
success_symbol = '[󱝂 ](fg:green)'
error_symbol = '[ 󰦍](fg:red)'
