##############################
# ╭─╮ ⋆ ✶ ✧ ✦ 󰫢 󰫣     󰘩
# │┼│      󱑽 ↵ ↪ ↝ ↜ ↩ ↳
# ╰─╯  󱝁  󱝂      󰖔 󰼱 
# ┏━┓ 󰆽           󰋇
# ┃╋┃  󰝨    󱃋   󰂖 󰉁 󱦟 
# ┗━┛          󰈸  󰞇
#      󰲼   󰳟     󰾞 󰦍 
##############################
format = """\
[╭](fg:current_line bold)[](fg:yellow)$username$hostname$time$fill$cmd_duration$c$python$aws$line_break\
[│](fg:current_line bold)[](fg:purple)$directory$fill$git_branch$git_status$line_break\
[╰](fg:current_line bold)[](fg:green)$character\
"""

palette = 'starlight'
add_newline = true

[palettes.dracula]
foreground = '#F8F8F2'
background = '#282A36'
current_line = '#44475A'
primary = '#1E1F29'
box = '#44475A'
blue = '#6272A4'
cyan = '#8BE9FD'
green = '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red = '#FF5555'
yellow = '#F1FA8C'

[palettes.starlight]
foreground = '#E9ECF5'
background = '#0B0E1A'
current_line = '#44475A'
primary = '#101421'
box = '#1C2236'
blue = '#7AA2F7'
cyan = '#8BE9FD'
green = '#7CE5A3'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#B4A1FF'
red = '#FF6B6B'
yellow = '#F6D97A'


[os]
format = '[✦](bold fg:blue)[ $symbol ](fg:foreground)[ ](bold fg:blue)'
disabled = true

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[username]
format = '[ 󰫢 ](bold fg:pink)[ ](bold fg:foreground)[$user](fg:foreground)[󱝁 ](bold fg:pink)'
show_always = true

[hostname]
format = '[󰖔 ](bold fg:cyan)[ ](bold fg:foreground)[$hostname](fg:foreground)[ ](bold fg:cyan)'
ssh_only = false
# trim_at = '.*'
disabled = false

[shell]
format = '[󰘩 ](bold fg:cyan)[ ](bold fg:foreground)[$indicator](fg:foreground)[ ](bold fg:cyan)'
disabled = true

[time]
format = '[ ](bold fg:yellow)[ ](bold fg:foreground)[$time](fg:foreground)[ ](bold fg:yellow)'
time_format = '%I:%M %p'
disabled = false

[nodejs]
format = '[✧ ](bold fg:orange)[$symbol](bold fg:foreground)[node.js:$version](fg:foreground)[ ](bold fg:orange)'
symbol = '󰎙 '

[python]
format = '[ ](bold fg:orange)[$symbol](bold fg:foreground)[python\($version\)](fg:foreground)[ ](bold fg:orange)'
symbol = ' '

[c]
format = '[✶ ](bold fg:blue)[$symbol](bold fg:foreground)[C:$version](fg:foreground)[ ](bold fg:blue)'
symbol = ' '

[aws]
format = '[󰫣 ](bold fg:purple)[$symbol](bold fg:foreground)[aws\($region\)$profile](fg:foreground)[ ](bold fg:purple)'
symbol = ' '

[fill]
# symbol = '─'
symbol = ''
style = 'fg:current_line'

[directory]
format = '[  ](bold fg:blue)[󰷏 ](bold fg:foreground)[$read_only$truncation_symbol$path](fg:foreground)[󰘩 ](bold fg:blue)'
home_symbol = '~'
truncation_symbol = '*'
truncation_length = 28
fish_style_pwd_dir_length = 1
read_only = '󱧵 '
read_only_style = ''

[git_branch]
format = '[ ](bold fg:red)[$symbol](bold fg:foreground)[$branch](fg:foreground)'
truncation_length = 24
truncation_symbol = '/'
symbol = '󰘬 '

[git_status]
format = '[(\($all_status\))](fg:foreground)[ ](bold fg:red)'

[cmd_duration]
min_time = 500
format = '[󰉁 ](bold fg:green)[󱦟](bold fg:foreground)[$duration](fg:foreground)[✶ ](bold fg:green)'

[character]
format = '[$symbol](fg:current_line) '
success_symbol = '[ ](fg:green)'
error_symbol = '[ 󰆽](fg:red)'
